from django.db import models
from django.contrib.auth.models import User
import django.utils.timezone

class Brewery(models.Model):

	brewery_name = models.CharField(max_length=50)

	COUNTRY_CHOICES = (
		('AF', 'Afganistan'),
		('AL', 'Albánsko'),
		('DZ', 'Alžírsko'),
		('AD', 'Andorra'),
		('AO', 'Angola'),
		('AI', 'Anguilla'),
		('AG', 'Antigua a Barbuda'),
		('AR', 'Argentína'),
		('AM', 'Arménsko'),
		('AW', 'Aruba'),
		('AU', 'Austrália'),
		('AZ', 'Azerbajdžan'),
		('BS', 'Bahamy'),
		('BH', 'Bahrajn'),
		('BD', 'Bangladéš'),
		('BB', 'Barbados'),
		('BE', 'Belgicko'),
		('BZ', 'Belize'),
		('BJ', 'Benin'),
		('BM', 'Bermudy'),
		('BT', 'Bhután'),
		('BY', 'Bielorusko'),
		('BO', 'Bolívia'),
		('BQ', 'Bonaire, Svätý Eustach a Saba'),
		('BA', 'Bosna a Hercegovina'),
		('BW', 'Botswana'),
		('BV', 'Bouvetov ostrov'),
		('BR', 'Brazília'),
		('VG', 'Britské Panenské ostrovy'),
		('BN', 'Brunej'),
		('BG', 'Bulharsko'),
		('BF', 'Burkina'),
		('BI', 'Burundi'),
		('CK', 'Cookove ostrovy'),
		('CW', 'Curacao'),
		('CY', 'Cyprus'),
		('TD', 'Čad'),
		('CZ', 'Česká republika'),
		('ME', 'Čierna Hora'),
		('CL', 'Čile'),
		('CN', 'Čína'),
		('DK', 'Dánsko'),
		('DM', 'Dominika'),
		('DO', 'Dominikánska republika'),
		('DJ', 'Džibutsko'),
		('EG', 'Egypt'),
		('EC', 'Ekvádor'),
		('ER', 'Eritrea'),
		('EE', 'Estónsko'),
		('ET', 'Etiópia'),
		('FO', 'Faerské ostrovy'),
		('FK', 'Falklandy'),
		('FJ', 'Fidži'),
		('PH', 'Filipíny'),
		('FI', 'Fínsko'),
		('FR', 'Francúzsko'),
		('GA', 'Gabon'),
		('GM', 'Gambia'),
		('GH', 'Ghana'),
		('GI', 'Gibraltár'),
		('GR', 'Grécko'),
		('GD', 'Grenada'),
		('GL', 'Grónsko'),
		('GE', 'Gruzínsko'),
		('GT', 'Guatemala'),
		('GG', 'Guernsey'),
		('GN', 'Guinea'),
		('GW', 'Guinea-Bissau'),
		('GY', 'Guyana'),
		('HT', 'Haiti'),
		('NL', 'Holandsko'),
		('HN', 'Honduras'),
		('HK', 'Hongkong'),
		('HR', 'Chorvátsko'),
		('IN', 'India'),
		('ID', 'Indonézia'),
		('XX', 'Iné'),
		('IQ', 'Irak'),
		('IR', 'Irán'),
		('IS', 'Island'),
		('IL', 'Izrael'),
		('IE', 'Írsko'),
		('JM', 'Jamajka'),
		('JP', 'Japonsko'),
		('YE', 'Jemen'),
		('JE', 'Jersey'),
		('JO', 'Jordánsko'),
		('ZA', 'Južná Afrika'),
		('GS', 'Južná Georgia a Južné Sandwichove ostrovy'),
		('SS', 'Južný Sudán'),
		('KY', 'Kajmanie ostrovy'),
		('KH', 'Kambodža'),
		('CM', 'Kamerun'),
		('CA', 'Kanada'),
		('CV', 'Kapverdy'),
		('QA', 'Katar'),
		('KZ', 'Kazachstan'),
		('KE', 'Keňa'),
		('KG', 'Kirgizsko'),
		('KI', 'Kiribati'),
		('CO', 'Kolumbia'),
		('KM', 'Komory'),
		('CD', 'Kongo (býv. Zair)'),
		('CG', 'Kongo'),
		('KR', 'Kórejská republika'),
		('KP', 'Kórejská ľudovodemokratická republika (KĽDR)'),
		('CR', 'Kostarika'),
		('CU', 'Kuba'),
		('KW', 'Kuvajt'),
		('LA', 'Laos'),
		('LS', 'Lesotho'),
		('LB', 'Libanon'),
		('LR', 'Libéria'),
		('LY', 'Líbya'),
		('LI', 'Lichtenštajnsko'),
		('LT', 'Litva'),
		('LV', 'Lotyšsko'),
		('LU', 'Luxembursko'),
		('MO', 'Macao'),
		('MK', 'Macedónsko'),
		('MG', 'Madagaskar'),
		('MY', 'Malajzia'),
		('MW', 'Malawi'),
		('MV', 'Maldivy'),
		('ML', 'Mali'),
		('MT', 'Malta'),
		('IM', 'Man'),
		('MA', 'Maroko'),
		('MU', 'Maurícius'),
		('MR', 'Mauritánia'),
		('HU', 'Maďarsko'),
		('MX', 'Mexiko'),
		('MM', 'Mjanmarsko'),
		('MD', 'Moldavsko'),
		('MC', 'Monako'),
		('MN', 'Mongolsko'),
		('MS', 'Montserrat'),
		('MZ', 'Mozambik'),
		('NA', 'Namíbia'),
		('NR', 'Nauru'),
		('DE', 'Nemecko'),
		('NP', 'Nepál'),
		('NE', 'Niger'),
		('NG', 'Nigéria'),
		('NI', 'Nikaragua'),
		('NO', 'Nórsko'),
		('NZ', 'Nový Zéland'),
		('OM', 'Omán '),
		('PK', 'Pakistan'),
		('PW', 'Palau'),
		('PA', 'Panama'),
		('PG', 'Papua-Nová Guinea'),
		('PY', 'Paraguaj'),
		('PE', 'Peru'),
		('CI', 'Pobrežie Slonoviny'),
		('PL', 'Poľsko'),
		('PT', 'Portugalsko'),
		('AT', 'Rakúsko'),
		('GQ', 'Rovníková Guinea'),
		('RO', 'Rumunsko'),
		('RU', 'Ruská federácia'),
		('RW', 'Rwanda'),
		('SV', 'Salvádor'),
		('WS', 'Samoa'),
		('SM', 'San Maríno'),
		('SA', 'Saudská Arábia'),
		('SN', 'Senegal'),
		('MP', 'Severné Mariány'),
		('SC', 'Seychely'),
		('SL', 'Sierra Leone'),
		('SG', 'Singapur'),
		('SK', 'Slovenská republika'),
		('SI', 'Slovinsko'),
		('SO', 'Somálsko'),
		('AE', 'Spojené arabské emiráty'),
		('US', 'Spojené štáty, USA'),
		('RS', 'Srbsko'),
		('LK', 'Srí Lanka'),
		('CF', 'Stredoafrická republika'),
		('SD', 'Sudán'),
		('SR', 'Surinam'),
		('SZ', 'Svazijsko'),
		('SH', 'Svätá Helena'),
		('LC', 'Svätá Lucia'),
		('KN', 'Svätý Krištof a Nevis'),
		('SX', 'Svätý Martin'),
		('ST', 'Svätý Tomáš a Princov ostrov'),
		('VC', 'Svätý Vincent a Grenadíny'),
		('SY', 'Sýria'),
		('SB', 'Šalamúnove ostrovy'),
		('ES', 'Španielsko'),
		('CH', 'Švajčiarsko'),
		('SE', 'Švédsko'),
		('TJ', 'Tadžikistan'),
		('TW', 'Taiwan'),
		('IT', 'Taliansko'),
		('TZ', 'Tanzánia'),
		('TH', 'Thajsko'),
		('TG', 'Togo'),
		('TO', 'Tonga'),
		('TT', 'Trinidad a Tobago'),
		('TN', 'Tunisko'),
		('TR', 'Turecko'),
		('TM', 'Turkménsko'),
		('TC', 'Turks a Caicos'),
		('TV', 'Tuvalu'),
		('UG', 'Uganda '),
		('UA', 'Ukrajina'),
		('UY', 'Uruguaj'),
		('UZ', 'Uzbekistan'),
		('VU', 'Vanuatu'),
		('VA', 'Vatikán'),
		('GB', 'Veľká Británia'),
		('VE', 'Venezuela'),
		('VN', 'Vietnam'),
		('TL', 'Východný Timor'),
		('ZM', 'Zambia'),
		('EH', 'Západná Sahara'),
		('ZW', 'Zimbabwe'),
	)
	country = models.CharField(max_length=30, choices=COUNTRY_CHOICES, default='SK')
	brewery_city = models.CharField(max_length=50, null=True, blank=True)

	def __str__(self):
		return self.brewery_name


class Beer(models.Model):
	brewery = models.ForeignKey(Brewery)
	beer_name = models.CharField(max_length=70)

	STYLE_CHOICES = (
			('altbier', 'Altbier'),
			('amber', 'Amber Ale'),
			('apa', 'APA'),
			('american_strong', 'American Strong Ale'),
			('baltic', 'Baltic Porter'),
			('barley_wine', 'Barley Wine'),
			('belgian', 'Belgian Ale'),
			('belgian_strong', 'Belgian Strong Ale'),
			('berliner_weisse', 'Berliner Weisse'),
			('biere_de_garde', 'Biere de Garde'),
			('bitter', 'Bitter'),
			('black_ipa', 'Black IPA'),
			('brown', 'Brown Ale'),
			('spice_herb_vegetable', 'Byliny/Korenie/Zelenina'),
			('california_common', 'California Common'),
			('cider', 'Cider'),
			('cream', 'Cream Ale'),
			('doppelbock', 'Doppelbock'),
			('dry_stout', 'Dry Stout'),
			('dubbel', 'Dubbel'),
			('dunkelweizen', 'Dunkelweizen'),
			('dunklerbock', 'Dunkler Bock'),
			('eisbock', 'Eisbock'),
			('epa', 'EPA'),
			('english_strong', 'English Strong Ale'),
			('foreign_stout', 'Foreign Stout'),
			('gose', 'Gose/Grodziskie'),
			('golden', 'Golden Ale/Blond Ale'),
			('hefeweizen', 'Hefeweizen'),
			('hellerbock', 'Heller Bock'),
			('helles', 'Helles'),
			('imperial_ipa', 'Imperial IPA/Double IPA'),
			('imperial_pils', 'Imperial Pils/Strong Lager'),
			('imperial_porter', 'Imperial Porter'),
			('imperial_stout', 'Imperial Stout'),
			('ipa', 'IPA'),
			('ipl', 'IPL'),
			('irish', 'Irish Ale'),
			('kolsch', 'Kölsch'),
			('kristallweizen', 'Kristallweizen'),
			('lambic', 'Lambic'),
			('marzen', 'Märzen/Oktoberfest'),
			('mild', 'Mild Ale'),
			('nealko', 'Nealkoholické'),
			('old', 'Old Ale'),
			('fruit', 'Ovocné'),
			('polotmavy', 'Polotmavý ležiak'),
			('porter', 'Porter'),
			('esb', 'Premium Bitter/ESB'),
			('quadrupel', 'Quadrupel'),
			('radler', 'Radler'),
			('sahti', 'Sahti'),
			('saison', 'Saison'),
			('scotch', 'Scotch Ale'),
			('scottish', 'Scottish Ale'),
			('session_ipa', 'Session IPA'),
			('sour', 'Sour Ale'),
			('stout', 'Stout'),
			('svetly', 'Svetlý ležiak'),
			('sweet_stout', 'Sweet Stout/Milk Stout'),
			('tmavy', 'Tmavý ležiak'),
			('traditional', 'Traditional Ale'),
			('tripel', 'Tripel'),
			('smoked', 'Údené'),
			('vienna', 'Viedenský ležiak'),
			('weizenbock', 'Weizen Bock'),
			('wheat', 'Wheat Ale'),
			('witbier', 'Witbier'),
			('zwickel', 'Zwickel/Keller'),
	)
	style = models.CharField(
		max_length=30,
		choices=STYLE_CHOICES,
		default='ipa'
	)

	plato = models.FloatField(null=True, blank=True)
	abv = models.FloatField(null=True, blank=True)

	def __str__(self):
		return self.brewery.brewery_name + " - " + self.beer_name

class Rating(models.Model):
	beer = models.ForeignKey(Beer)
	user = models.ForeignKey(User)

	city = models.CharField(max_length=50)
	place = models.CharField(max_length=70, null=True, blank=True)

	SERVING_CHOICES = (
		(True, 'fľašové'),
		(False, 'čapované'),
	)
	serving = models.BooleanField(choices=SERVING_CHOICES, default=True) # sud alebo flasa

	date = models.DateField(default=django.utils.timezone.now)
	price = models.FloatField(null=True, blank=True)

	DECI = 0.1
	DVE_DECI = 0.2
	MALE = 0.3
	MALA_FLASA = 0.33
	STVORKA = 0.4
	VELKE = 0.5
	SEDMICKA = 0.75
	LITER = 1
	VOLUME_CHOICES = (
		(DECI, '0,1l'),
		(DVE_DECI, '0,2l'),
		(MALE, '0,3l'),
		(MALA_FLASA, '0,33l'),
		(STVORKA, '0,4l'),
		(VELKE, '0,5l'),
		(SEDMICKA, '0,75l'),
		(LITER, '1l'),
	)
	volume = models.FloatField(max_length=10, choices=VOLUME_CHOICES, default=VELKE) # choices

	note = models.TextField(null=True, blank=True)

	ZLE = 1
	PODPRIEMER = 2
	PRIEMER = 3
	NADPRIEMER = 4
	SUPER = 5
	RATING_CHOICES = (
		(ZLE, '1'),
		(PODPRIEMER, '2'),
		(PRIEMER, '3'),
		(NADPRIEMER, '4'),
		(SUPER, '5'),
	)
	rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES, default=PRIEMER) #choices

	def __str__(self):
		return self.user.username + " - " + self.beer.brewery.brewery_name + " - " + self.beer.beer_name