# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=70)),
                ('style', models.CharField(max_length=10)),
                ('plato', models.IntegerField()),
                ('abv', models.FloatField()),
                ('city', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=70)),
                ('note', models.TextField()),
            ],
        ),
    ]
