# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20170731_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(choices=[('ale', 'Ale'), ('lager', 'Ležiak')], default='ale', max_length=10),
        ),
    ]
