# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20170731_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
