# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20170731_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='country',
            field=models.CharField(choices=[('SK', 'Slovensko'), ('CZ', 'Česká republika'), ('US', 'USA')], default='SK', max_length=30),
        ),
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='plato',
            field=models.FloatField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='price',
            field=models.FloatField(blank=True, default=1.5, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(choices=[('ale', 'Ale'), ('lager', 'Ležiak')], default='lager', max_length=10),
        ),
    ]
