# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_auto_20170731_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='volume',
            field=models.FloatField(choices=[(0.1, '0,1l'), (0.2, '0,2l'), (0.33, '0,33l'), (0.4, '0.4l'), (0.5, '0,5l'), (0.75, '0,75l'), (1, '1l')], default=0.5, max_length=10),
        ),
    ]
