# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0011_auto_20170811_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
