# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0012_auto_20170811_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(choices=[('altbier', 'Altbier'), ('amber', 'Amber Ale'), ('apa', 'APA'), ('american_strong', 'American Strong Ale'), ('baltic', 'Baltic Porter'), ('barley_wine', 'Barley Wine'), ('belgian', 'Belgian Ale'), ('belgian_strong', 'Belgian Strong Ale'), ('berliner_weisse', 'Berliner Weisse'), ('biere_de_garde', 'Biere de Garde'), ('bitter', 'Bitter'), ('black_ipa', 'Black IPA'), ('brown', 'Brown Ale'), ('spice_herb_vegetable', 'Byliny/Korenie/Zelenina'), ('california_common', 'California Common'), ('cider', 'Cider'), ('cream', 'Cream Ale'), ('doppelbock', 'Doppelbock'), ('dry_stout', 'Dry Stout'), ('dubbel', 'Dubbel'), ('dunkelweizen', 'Dunkelweizen'), ('dunklerbock', 'Dunkler Bock'), ('eisbock', 'Eisbock'), ('epa', 'EPA'), ('english_strong', 'English Strong Ale'), ('foreign_stout', 'Foreign Stout'), ('gose', 'Gose/Grodziskie'), ('golden', 'Golden Ale/Blond Ale'), ('hefeweizen', 'Hefeweizen'), ('hellerbock', 'Heller Bock'), ('helles', 'Helles'), ('imperial_ipa', 'Imperial IPA/Double IPA'), ('imperial_pils', 'Imperial Pils/Strong Lager'), ('imperial_porter', 'Imperial Porter'), ('imperial_stout', 'Imperial Stout'), ('ipa', 'IPA'), ('ipl', 'IPL'), ('irish', 'Irish Ale'), ('kolsch', 'Kölsch'), ('kristallweizen', 'Kristallweizen'), ('lambic', 'Lambic'), ('marzen', 'Märzen/Oktoberfest'), ('mild', 'Mild Ale'), ('nealko', 'Nealkoholické'), ('old', 'Old Ale'), ('fruit', 'Ovocné'), ('polotmavy', 'Polotmavý ležiak'), ('porter', 'Porter'), ('esb', 'Premium Bitter/ESB'), ('quadrupel', 'Quadrupel'), ('radler', 'Radler'), ('sahti', 'Sahti'), ('saison', 'Saison'), ('scotch', 'Scotch Ale'), ('scottish', 'Scottish Ale'), ('session_ipa', 'Session IPA'), ('sour', 'Sour Ale'), ('stout', 'Stout'), ('svetly', 'Svetlý ležiak'), ('sweet_stout', 'Sweet Stout/Milk Stout'), ('tmavy', 'Tmavý ležiak'), ('traditional', 'Traditional Ale'), ('tripel', 'Tripel'), ('smoked', 'Údené'), ('vienna', 'Viedenský ležiak'), ('weizenbock', 'Weizen Bock'), ('wheat', 'Wheat Ale'), ('witbier', 'Witbier'), ('zwickel', 'Zwickel/Keller')], default='ipa', max_length=30),
        ),
    ]
