# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0015_auto_20170816_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='name',
            new_name='beer_name',
        ),
        migrations.RenameField(
            model_name='brewery',
            old_name='brewery',
            new_name='brewery_name',
        ),
    ]
