# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0020_auto_20171019_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (666, '666')], default=3),
        ),
    ]
